[build]
  publish = "."
  command = ""

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/dashboard/data/*"
  [headers.values]
    Cache-Control = "no-cache"
